### ISSUE TITLE
Need help with proxying ID3D12GraphicsCommandList methods.

### ISSUE THREAD

**Issue by joltzbronzer** [cdozdil/d3d12-proxy#2]
How would I go about proxying ID3D12GraphicsCommandList methods inside d3d12-proxy?

**Comment by cdozdil** [comment]
Probably you can follow same pattern that I used with dxgi-proxy. You can check it here -> [dllmain.c](https://github.com/cdozdil/d3d12-proxy/blob/master/dxgi-proxy/dllmain.cpp)

**Comment by cdozdil** [comment]
I would suggets you to check RenderDoc source, they have wrapped almost all D3D12 interfaces. You can check CommandList here for example -> [ID3D12GraphicsCommandList](https://github.com/baldurk/renderdoc/blob/10d402358cb5eac9d35bc66216eb77eddc6e9098/renderdoc/driver/d3d12/d3d12_command_list.h#L148)
