### ISSUE TITLE
dxgi-proxy log files

### ISSUE THREAD

**Issue by Ekidoxx** [cdozdil/d3d12-proxy#3]
Got your `dxgi.dll` from [mod replacing DLSS with FSR2](https://www.nexusmods.com/palworld/mods/63?tab=description) and now every time game is launched, new `dxgi-proxy-<date>_<time>.log` is created. Even though the files are small, I just noticed I have 30 of them in my directory.

Is there any way to disable creation of the logs? Like creating new file `dxgi.ini` with `Silent=true` value (Kinda hoped for [this troubleshooting](https://steamcommunity.com/app/208650/discussions/0/520519112497419885) method to work, but it doesn't 😅), or adding more parameters to game executable next to `-dx12`?

_*I know that you're not the mod author, but since it uses your release (v0.1), I thought that you will know better..._

**Comment by cdozdil** [comment]
actually it was bugging me for some time too, so here you go. [v0.1.1](https://github.com/cdozdil/d3d12-proxy/releases/tag/v0.1.1) aka v0.1 but logging disabled :)

**Comment by Ekidoxx** [comment]
Thank you very much 💖
